### PR TITLE
file maintainer please do make necessary

### PR DESCRIPTION
**Pull request by utkarshtambe10**
As, according to this structure of file, we are not able to add our team details as prescribed by sir. Thanks in advance!

### CODE REVIEW

**Review by VikashPR — APPROVED** [review]
👍🏽

**Comment by VikashPR** [comment]
> As, according to this structure of file, we are not able to add our team details as prescribed by sir. Thanks in advance!

Much appreciated @utkarshtambe10 thank you for making PullRequest 🚀

**Comment by VikashPR** [comment]
@all-contributors please add @utkarshtambe10 for example, maintenance

**Comment by utkarshtambe10** [comment]
Yeah sure. Welcome!

**Pull request merged**
